DROP SEQUENCE eldappstafd_seq;

DROP SEQUENCE eldcroretdayfd_seq;

DROP SEQUENCE elddatenvfd_seq;

DROP SEQUENCE elddatlisfd_seq;

DROP SEQUENCE elddatpasfd_seq;

DROP SEQUENCE elddelpasfd_seq;

DROP SEQUENCE elddepdetfd_seq;

DROP SEQUENCE elddepfd_seq;

DROP SEQUENCE elddepownfd_seq;

DROP SEQUENCE elddepreqfd_seq;

DROP SEQUENCE elddepreqrepfilmapfd_seq;

DROP SEQUENCE elddepreqschfd_seq;

DROP SEQUENCE elddepreqstafd_seq;

DROP SEQUENCE elddepscrstafd_seq;

DROP SEQUENCE elddepstafd_seq;

DROP SEQUENCE eldfiltypfd_seq;

DROP SEQUENCE eldmapfordbfd_seq;

DROP SEQUENCE eldmapforrepfd_seq;

DROP SEQUENCE eldpasrestokfd_seq;

DROP SEQUENCE eldprostodbfd_seq;

DROP SEQUENCE eldrepforrolfd_seq;

DROP SEQUENCE eldrepforteafd_seq;

DROP SEQUENCE eldrepuseaccfd_seq;

DROP SEQUENCE eldreqaudfd_seq;

DROP SEQUENCE eldrolforteafd_seq;

DROP SEQUENCE eldroluseaccfd_seq;

DROP SEQUENCE eldsesparfd_seq;

DROP SEQUENCE eldteaforusefd_seq;

DROP SEQUENCE eldusefd_seq;

DROP SEQUENCE elduserolfd_seq;

DROP SEQUENCE ELDUSERUIPREFFD_SEQ;

DROP SEQUENCE  ELDMFAAUDTRAFD_SEQ ;

DROP SEQUENCE  ELDMFAUSERAUDTRAFD_SEQ;

DROP SEQUENCE  ELDREPTOUCHCNTFD_SEQ;

DROP TABLE eldappmgmfd CASCADE CONSTRAINTS;

DROP TABLE eldappstafd CASCADE CONSTRAINTS;

DROP TABLE eldcomfd CASCADE CONSTRAINTS;

DROP TABLE eldcroretdayfd CASCADE CONSTRAINTS;

DROP TABLE elddatenvfd CASCADE CONSTRAINTS;

DROP TABLE elddatlisfd CASCADE CONSTRAINTS;

DROP TABLE eldusestatfd CASCADE CONSTRAINTS;

DROP TABLE elddatpasfd CASCADE CONSTRAINTS;

DROP TABLE elddelpasfd CASCADE CONSTRAINTS;

DROP TABLE elddepdetfd CASCADE CONSTRAINTS;

DROP TABLE elddepdethisfd CASCADE CONSTRAINTS;

DROP TABLE elddepfd CASCADE CONSTRAINTS;

DROP TABLE elddephisfd CASCADE CONSTRAINTS;

DROP TABLE elddepownbacfd CASCADE CONSTRAINTS;

DROP TABLE elddepownfd CASCADE CONSTRAINTS;

DROP TABLE elddepprifd CASCADE CONSTRAINTS;

DROP TABLE elddepreqfd CASCADE CONSTRAINTS;

DROP TABLE elddepreqfilhisfd CASCADE CONSTRAINTS;

DROP TABLE elddepreqhisfd CASCADE CONSTRAINTS;

DROP TABLE elddepreqrepfilmapfd CASCADE CONSTRAINTS;

DROP TABLE elddepreqschfd CASCADE CONSTRAINTS;

DROP TABLE elddepreqstafd CASCADE CONSTRAINTS;

DROP TABLE elddepscrstafd CASCADE CONSTRAINTS;

DROP TABLE elddepstafd CASCADE CONSTRAINTS;

DROP TABLE eldfiltypfd CASCADE CONSTRAINTS;

DROP TABLE eldmapfd CASCADE CONSTRAINTS;

DROP TABLE eldmapfordbfd CASCADE CONSTRAINTS;

DROP TABLE eldmapforrepfd CASCADE CONSTRAINTS;

DROP TABLE eldpasrestokfd CASCADE CONSTRAINTS;

DROP TABLE eldprostodbfd CASCADE CONSTRAINTS;

DROP TABLE eldrepforrolfd CASCADE CONSTRAINTS;

DROP TABLE eldrepforteafd CASCADE CONSTRAINTS;

DROP TABLE eldreptabfd CASCADE CONSTRAINTS;

DROP TABLE eldrepuseaccfd CASCADE CONSTRAINTS;

DROP TABLE eldreqaudfd CASCADE CONSTRAINTS;

DROP TABLE eldrolforteafd CASCADE CONSTRAINTS;

DROP TABLE eldroltabfd CASCADE CONSTRAINTS;

DROP TABLE eldroluseaccfd CASCADE CONSTRAINTS;

DROP TABLE eldsesparfd CASCADE CONSTRAINTS;

DROP TABLE eldteaforusefd CASCADE CONSTRAINTS;

DROP TABLE eldteanamfd CASCADE CONSTRAINTS;

DROP TABLE eldusefd CASCADE CONSTRAINTS;

DROP TABLE elduserolfd CASCADE CONSTRAINTS;

DROP TABLE eldwraconfd CASCADE CONSTRAINTS;

DROP TABLE ELDUSERUIPREFFD CASCADE CONSTRAINTS;

DROP TABLE ELDUSEEMAIPREFD CASCADE CONSTRAINTS;

DROP TABLE ELDMFAAUDTRAFD  CASCADE CONSTRAINTS;

DROP TABLE ELDMFAUSERAUDTRAFD  CASCADE CONSTRAINTS;

DROP TABLE ELDREPTOUCHCNTFD  CASCADE CONSTRAINTS;


