#spring:
#  application:
#    name: gateway-service
#  cloud:
#    gateway:
#      routes:
#        - id: booking-service
#          uri: http://localhost:9091
#          predicates:
#            - Path=/booking/
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#
#server:
#  port: 9090
